name = input("What is your name? ")
add = input("What is your address, city, state, and zip? ")
tel = input("What is your telephone number? ")
major = input("What was your college major? ")
print(name, add, tel, major)
